import product from "../../assets/product.png";

export const servicesData = [
  {
    id: "1",
    title: "Raspberry Pi 4 (With Wifi)",
    price: "Rs 50,080",
    oldPrice: "₹3,029.50",
    size: "16 Gb",
    rating: 4.5,
    reviews: 392,
    sold: 1241,
    modelNumbers: ["Hh3", "Gh2"],
    colors: ["black", "green", "blue"],
    features: ["Central Processing Unit (CPU)", "Memory Unit", "SD Card Slot"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "2",
    title: "Arduino Uno R3",
    price: "Rs 12,000",
    oldPrice: "₹2,029.00",
    size: "8 Gb",
    rating: 4.2,
    reviews: 198,
    sold: 840,
    modelNumbers: ["A1", "B2"],
    colors: ["blue", "white"],
    features: ["Microcontroller", "USB Interface", "Power Jack"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "1",
    title: "Raspberry Pi 4 (With Wifi)",
    price: "Rs 50,080",
    oldPrice: "₹3,029.50",
    size: "16 Gb",
    rating: 4.5,
    reviews: 392,
    sold: 1241,
    modelNumbers: ["Hh3", "Gh2"],
    colors: ["black", "green", "blue"],
    features: ["Central Processing Unit (CPU)", "Memory Unit", "SD Card Slot"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "2",
    title: "Arduino Uno R3",
    price: "Rs 12,000",
    oldPrice: "₹2,029.00",
    size: "8 Gb",
    rating: 4.2,
    reviews: 198,
    sold: 840,
    modelNumbers: ["A1", "B2"],
    colors: ["blue", "white"],
    features: ["Microcontroller", "USB Interface", "Power Jack"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "1",
    title: "Raspberry Pi 4 (With Wifi)",
    price: "Rs 50,080",
    oldPrice: "₹3,029.50",
    size: "16 Gb",
    rating: 4.5,
    reviews: 392,
    sold: 1241,
    modelNumbers: ["Hh3", "Gh2"],
    colors: ["black", "green", "blue"],
    features: ["Central Processing Unit (CPU)", "Memory Unit", "SD Card Slot"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "1",
    title: "Raspberry Pi 4 (With Wifi)",
    price: "Rs 50,080",
    oldPrice: "₹3,029.50",
    size: "16 Gb",
    rating: 4.5,
    reviews: 392,
    sold: 1241,
    modelNumbers: ["Hh3", "Gh2"],
    colors: ["black", "green", "blue"],
    features: ["Central Processing Unit (CPU)", "Memory Unit", "SD Card Slot"],
    image: product,
    thumbnails: [product, product, product, product],
  },
  {
    id: "2",
    title: "Arduino Uno R3",
    price: "Rs 12,000",
    oldPrice: "₹2,029.00",
    size: "8 Gb",
    rating: 4.2,
    reviews: 198,
    sold: 840,
    modelNumbers: ["A1", "B2"],
    colors: ["blue", "white"],
    features: ["Microcontroller", "USB Interface", "Power Jack"],
    image: product,
    thumbnails: [product, product, product, product],
  },

];
